// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg6WFfGcW2WuYLb_0FvgfD18r4rI2TMPg',
    appId: '1:685843397990:web:241bba0a8fb6bdd50ddca7',
    messagingSenderId: '685843397990',
    projectId: 'medicine-reminder-app-e1023',
    authDomain: 'medicine-reminder-app-e1023.firebaseapp.com',
    storageBucket: 'medicine-reminder-app-e1023.appspot.com',
    measurementId: 'G-DFXDVMGVW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPnGh2UtB7yMjSo_t3fTK9C_Pt2LuuiDQ',
    appId: '1:685843397990:android:1bc1431e3b6cb6710ddca7',
    messagingSenderId: '685843397990',
    projectId: 'medicine-reminder-app-e1023',
    storageBucket: 'medicine-reminder-app-e1023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzMg6M6FmKgrb-_ZeiVYg8qs6ddJHeaA',
    appId: '1:685843397990:ios:3b49a7eb68b6448e0ddca7',
    messagingSenderId: '685843397990',
    projectId: 'medicine-reminder-app-e1023',
    storageBucket: 'medicine-reminder-app-e1023.appspot.com',
    iosClientId: '685843397990-augr6s31h38idc5oqvp1riae8ebf9tpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZzMg6M6FmKgrb-_ZeiVYg8qs6ddJHeaA',
    appId: '1:685843397990:ios:3b49a7eb68b6448e0ddca7',
    messagingSenderId: '685843397990',
    projectId: 'medicine-reminder-app-e1023',
    storageBucket: 'medicine-reminder-app-e1023.appspot.com',
    iosClientId: '685843397990-augr6s31h38idc5oqvp1riae8ebf9tpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineReminderApp',
  );
}
